import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// title desc and heads of pages
// layout can go for specific pages as well as test/ layout.js that has layout for test page
// image directly in app folder with name icon will be icon default
// @import for directly importing components from root dir to the place we want to use them done by jsconfig file

// special file names , not-found / error / route.js to create and return api data

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
